<?php

use App\Http\Controllers\CounterController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\ProjectionController;
use App\Http\Controllers\PromptTemplateController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\TransportationLogController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\TransactionLogPageController;
use App\Http\Controllers\VarianceAnalysisController;
use App\Http\Controllers\WorkdayController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/counter');
Route::get('/counter', [CounterController::class, 'index'])->name('counter');
Route::get('/settings', [SettingsController::class, 'index'])->name('settings.index');
Route::post('/settings/prompt-templates', [PromptTemplateController::class, 'store'])->name('settings.prompt-templates.store');
Route::put('/settings/prompt-templates/{promptTemplate}', [PromptTemplateController::class, 'update'])->name('settings.prompt-templates.update');
Route::delete('/settings/prompt-templates/{promptTemplate}', [PromptTemplateController::class, 'destroy'])->name('settings.prompt-templates.destroy');
Route::post('/settings/prompt-templates/compose', [PromptTemplateController::class, 'compose'])->name('settings.prompt-templates.compose');
Route::get('/transaction-log', [TransactionLogPageController::class, 'index'])->name('transaction-log.index');
Route::get('/transportation-log', [TransportationLogController::class, 'index'])->name('transportation-log.index');
Route::get('/transportation-log/snapshot', [TransportationLogController::class, 'snapshot'])->name('transportation-log.snapshot');
Route::post('/transportation-log/export', [TransportationLogController::class, 'export'])->name('transportation-log.export');
Route::post('/transportation-log/vehicles', [TransportationLogController::class, 'storeVehicle'])->name('transportation-log.vehicles.store');
Route::put('/transportation-log/vehicles/{vehicle}', [TransportationLogController::class, 'updateVehicle'])->name('transportation-log.vehicles.update');
Route::delete('/transportation-log/vehicles/{vehicle}', [TransportationLogController::class, 'destroyVehicle'])->name('transportation-log.vehicles.destroy');
Route::post('/transportation-log/fuel-logs', [TransportationLogController::class, 'storeFuelLog'])->name('transportation-log.fuel-logs.store');
Route::put('/transportation-log/fuel-logs/{fuelLog}', [TransportationLogController::class, 'updateFuelLog'])->name('transportation-log.fuel-logs.update');
Route::delete('/transportation-log/fuel-logs/{fuelLog}', [TransportationLogController::class, 'destroyFuelLog'])->name('transportation-log.fuel-logs.destroy');
Route::post('/transportation-log/commute-logs', [TransportationLogController::class, 'storeCommuteLog'])->name('transportation-log.commute-logs.store');
Route::put('/transportation-log/commute-logs/{commuteLog}', [TransportationLogController::class, 'updateCommuteLog'])->name('transportation-log.commute-logs.update');
Route::delete('/transportation-log/commute-logs/{commuteLog}', [TransportationLogController::class, 'destroyCommuteLog'])->name('transportation-log.commute-logs.destroy');
Route::post('/transportation-log/parking-logs', [TransportationLogController::class, 'storeParkingLog'])->name('transportation-log.parking-logs.store');
Route::put('/transportation-log/parking-logs/{parkingLog}', [TransportationLogController::class, 'updateParkingLog'])->name('transportation-log.parking-logs.update');
Route::delete('/transportation-log/parking-logs/{parkingLog}', [TransportationLogController::class, 'destroyParkingLog'])->name('transportation-log.parking-logs.destroy');
Route::redirect('/fuel-log', '/transportation-log');
Route::get('/projection', [ProjectionController::class, 'index'])->name('projection.index');
Route::post('/projection/run', [ProjectionController::class, 'run'])->name('projection.run');
Route::post('/projection/scenarios', [ProjectionController::class, 'saveScenario'])->name('projection.scenarios.save');
Route::get('/projection/scenarios/{scenario}', [ProjectionController::class, 'showScenario'])->name('projection.scenarios.show');
Route::delete('/projection/scenarios/{scenario}', [ProjectionController::class, 'destroyScenario'])->name('projection.scenarios.delete');
Route::post('/projection/compare', [ProjectionController::class, 'compare'])->name('projection.compare');
Route::get('/variance-analysis', [VarianceAnalysisController::class, 'index'])->name('variance-analysis.index');
Route::get('/variance-analysis/scenarios/{scenario}', [VarianceAnalysisController::class, 'showScenario'])->name('variance-analysis.scenarios.show');
Route::post('/variance-analysis/scenarios/{scenario}/actuals', [VarianceAnalysisController::class, 'saveActuals'])->name('variance-analysis.scenarios.actuals.save');
Route::get('/history', [HistoryController::class, 'index'])->name('history.index');
Route::get('/history/months', [HistoryController::class, 'months'])->name('history.months');
Route::post('/history/months', [HistoryController::class, 'saveMonth'])->name('history.months.save');
Route::put('/history/months/{month}', [HistoryController::class, 'updateMonth'])->name('history.months.update');

Route::get('/counter/snapshot', [CounterController::class, 'snapshot'])->name('counter.snapshot');
Route::post('/transactions', [TransactionController::class, 'store'])->name('transactions.store');
Route::patch('/transactions/{transaction}', [TransactionController::class, 'update'])->name('transactions.update');
Route::delete('/transactions/{transaction}', [TransactionController::class, 'destroy'])->name('transactions.destroy');
Route::patch('/workdays/{workday}', [WorkdayController::class, 'update'])->name('workdays.update');
